package com.donglu.carpark.yun;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-11T15:54:40.606+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "RQDataExchangeSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RQDataExchangeSoap {

    @WebMethod(operationName = "WriteDBDate", action = "http://tempuri.org/WriteDBDate")
    @RequestWrapper(localName = "WriteDBDate", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.WriteDBDate")
    @ResponseWrapper(localName = "WriteDBDateResponse", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.WriteDBDateResponse")
    @WebResult(name = "WriteDBDateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String writeDBDate(
        @WebParam(name = "as_XmlData", targetNamespace = "http://tempuri.org/")
        java.lang.String asXmlData
    );

    @WebMethod(operationName = "ReadDBDate", action = "http://tempuri.org/ReadDBDate")
    @RequestWrapper(localName = "ReadDBDate", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.ReadDBDate")
    @ResponseWrapper(localName = "ReadDBDateResponse", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.ReadDBDateResponse")
    @WebResult(name = "ReadDBDateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String readDBDate(
        @WebParam(name = "as_XmlData", targetNamespace = "http://tempuri.org/")
        java.lang.String asXmlData
    );

    @WebMethod(operationName = "WriteHTDate", action = "http://tempuri.org/WriteHTDate")
    @RequestWrapper(localName = "WriteHTDate", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.WriteHTDate")
    @ResponseWrapper(localName = "WriteHTDateResponse", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.WriteHTDateResponse")
    @WebResult(name = "WriteHTDateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String writeHTDate(
        @WebParam(name = "as_XmlData", targetNamespace = "http://tempuri.org/")
        java.lang.String asXmlData
    );

    @WebMethod(operationName = "MonthCardData", action = "http://tempuri.org/MonthCardData")
    @RequestWrapper(localName = "MonthCardData", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.MonthCardData")
    @ResponseWrapper(localName = "MonthCardDataResponse", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.MonthCardDataResponse")
    @WebResult(name = "MonthCardDataResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String monthCardData(
        @WebParam(name = "as_XmlData", targetNamespace = "http://tempuri.org/")
        java.lang.String asXmlData
    );

    @WebMethod(operationName = "EntereData", action = "http://tempuri.org/EntereData")
    @RequestWrapper(localName = "EntereData", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.EntereData")
    @ResponseWrapper(localName = "EntereDataResponse", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.EntereDataResponse")
    @WebResult(name = "EntereDataResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String entereData(
        @WebParam(name = "as_XmlData", targetNamespace = "http://tempuri.org/")
        java.lang.String asXmlData
    );

    @WebMethod(operationName = "ChargesData", action = "http://tempuri.org/ChargesData")
    @RequestWrapper(localName = "ChargesData", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.ChargesData")
    @ResponseWrapper(localName = "ChargesDataResponse", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.ChargesDataResponse")
    @WebResult(name = "ChargesDataResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String chargesData(
        @WebParam(name = "as_XmlData", targetNamespace = "http://tempuri.org/")
        java.lang.String asXmlData
    );

    @WebMethod(operationName = "WorkingData", action = "http://tempuri.org/WorkingData")
    @RequestWrapper(localName = "WorkingData", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.WorkingData")
    @ResponseWrapper(localName = "WorkingDataResponse", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.WorkingDataResponse")
    @WebResult(name = "WorkingDataResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String workingData(
        @WebParam(name = "as_XmlData", targetNamespace = "http://tempuri.org/")
        java.lang.String asXmlData
    );

    @WebMethod(operationName = "VehicleData", action = "http://tempuri.org/VehicleData")
    @RequestWrapper(localName = "VehicleData", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.VehicleData")
    @ResponseWrapper(localName = "VehicleDataResponse", targetNamespace = "http://tempuri.org/", className = "com.donglu.carpark.yun.VehicleDataResponse")
    @WebResult(name = "VehicleDataResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String vehicleData(
        @WebParam(name = "as_XmlData", targetNamespace = "http://tempuri.org/")
        java.lang.String asXmlData
    );
}
