package com.donglu.carpark.yun;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-11T15:54:40.613+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "RQDataExchange", 
                  wsdlLocation = "http://112.124.115.117/WebService/RQDataExchange.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class RQDataExchange extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "RQDataExchange");
    public final static QName RQDataExchangeSoap = new QName("http://tempuri.org/", "RQDataExchangeSoap");
    public final static QName RQDataExchangeSoap12 = new QName("http://tempuri.org/", "RQDataExchangeSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://112.124.115.117/WebService/RQDataExchange.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RQDataExchange.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://112.124.115.117/WebService/RQDataExchange.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public RQDataExchange(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RQDataExchange(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RQDataExchange() {
        super(WSDL_LOCATION, SERVICE);
    }
    



    /**
     *
     * @return
     *     returns RQDataExchangeSoap
     */
    @WebEndpoint(name = "RQDataExchangeSoap")
    public RQDataExchangeSoap getRQDataExchangeSoap() {
        return super.getPort(RQDataExchangeSoap, RQDataExchangeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RQDataExchangeSoap
     */
//    @WebEndpoint(name = "RQDataExchangeSoap")
//    public RQDataExchangeSoap getRQDataExchangeSoap(WebServiceFeature... features) {
//        return super.getPort(RQDataExchangeSoap, RQDataExchangeSoap.class, features);
//    }


    /**
     *
     * @return
     *     returns RQDataExchangeSoap
     */
    @WebEndpoint(name = "RQDataExchangeSoap12")
    public RQDataExchangeSoap getRQDataExchangeSoap12() {
        return super.getPort(RQDataExchangeSoap12, RQDataExchangeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RQDataExchangeSoap
     */
//    @WebEndpoint(name = "RQDataExchangeSoap12")
//    public RQDataExchangeSoap getRQDataExchangeSoap12(WebServiceFeature... features) {
//        return super.getPort(RQDataExchangeSoap12, RQDataExchangeSoap.class, features);
//    }

}
