
package com.donglu.carpark.yun;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-11T15:54:40.564+08:00
 * Generated source version: 3.1.4
 * 
 */
public final class RQDataExchangeSoap_RQDataExchangeSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "RQDataExchange");

    private RQDataExchangeSoap_RQDataExchangeSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RQDataExchange.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RQDataExchange ss = new RQDataExchange(wsdlURL, SERVICE_NAME);
        RQDataExchangeSoap port = ss.getRQDataExchangeSoap();  
        
//        {
//        System.out.println("Invoking writeDBDate...");
//        java.lang.String _writeDBDate_asXmlData = "";
//        java.lang.String _writeDBDate__return = port.writeDBDate(_writeDBDate_asXmlData);
//        System.out.println("writeDBDate.result=" + _writeDBDate__return);
//
//
//        }
//        {
//        System.out.println("Invoking readDBDate...");
//        java.lang.String _readDBDate_asXmlData = "";
//        java.lang.String _readDBDate__return = port.readDBDate(_readDBDate_asXmlData);
//        System.out.println("readDBDate.result=" + _readDBDate__return);
//
//
//        }
//        {
//        System.out.println("Invoking writeHTDate...");
//        java.lang.String _writeHTDate_asXmlData = "";
//        java.lang.String _writeHTDate__return = port.writeHTDate(_writeHTDate_asXmlData);
//        System.out.println("writeHTDate.result=" + _writeHTDate__return);
//
//
//        }
        {
        System.out.println("Invoking monthCardData...");
        java.lang.String _monthCardData_asXmlData = "<Root LicenseNumber =\"粤B48793\" KaTypeName=\"年卡\"  "
        		+ "CLAdder=\"科技园\"  CLName=\"孟杰\" CLDH=\"13798363670\" StartDate =\"2014-9-9\" EndDate =\"2014-10-1\" DutyNumber =\"A009\" DutyName =\"小孟\" ChargesAmount =\"200\" Company =\"深圳凯龙国际酒店\" Area=\"凯龙酒店停车场\"></Root>";
        java.lang.String _monthCardData__return = port.monthCardData(_monthCardData_asXmlData);
        System.out.println("monthCardData.result====" + _monthCardData__return);


        }
//        {
//        System.out.println("Invoking entereData...");
//        java.lang.String _entereData_asXmlData = "";
//        java.lang.String _entereData__return = port.entereData(_entereData_asXmlData);
//        System.out.println("entereData.result=" + _entereData__return);
//
//
//        }
//        {
//        System.out.println("Invoking chargesData...");
//        java.lang.String _chargesData_asXmlData = "";
//        java.lang.String _chargesData__return = port.chargesData(_chargesData_asXmlData);
//        System.out.println("chargesData.result=" + _chargesData__return);
//
//
//        }
//        {
//        System.out.println("Invoking workingData...");
//        java.lang.String _workingData_asXmlData = "";
//        java.lang.String _workingData__return = port.workingData(_workingData_asXmlData);
//        System.out.println("workingData.result=" + _workingData__return);
//
//
//        }
//        {
//        System.out.println("Invoking vehicleData...");
//        java.lang.String _vehicleData_asXmlData = "";
//        java.lang.String _vehicleData__return = port.vehicleData(_vehicleData_asXmlData);
//        System.out.println("vehicleData.result=" + _vehicleData__return);
//
//
//        }

        System.exit(0);
    }

}
